// STATE-DATA: estado global da aplicação (State) e dicionário padrão (seed).

    // ═══════════════════════════════════════════════════════════
    // ESTADO GLOBAL
    // ═══════════════════════════════════════════════════════════
    const RENDER_AHEAD = 2;   // páginas renderizadas para cada lado da atual
    const RENDER_KEEP_MARGIN = 5; // além disso, canvas é liberado da memória

    const State = {
      pdf: null,
      pageCount: 0,
      scale: 1.3,
      currentPage: 1,
      activePages: new Set(), // Páginas com interatividade ativa (texto/tradução)
      renderedPages: new Map(), // pageNum -> {page, viewport, wrapper, canvas, textLayer, ctx, rendered, renderTask, textContent}
      dictionary: {},
      suffixDict: {},
      currentWord: null,
      editTranslations: [],
      editExamples: [],
      editSuffixExamples: [],
      filename: '',
      intersectionObserver: null,
      renderObserver: null, // observer de virtualização (renderiza/libera canvases)
      pdfSearchIndex: new Map(), // pageNum -> texto puro da página (cache p/ busca)
      pdfSearchFocusIdx: -1,
      pdfSearchResults: [],
      lastPageSaveTimer: null,
      // ── Novo: Prática (repetição espaçada) ──
      practiceData: {}, // persistido via IndexedDB: { [word]: { box, timesSeen, timesCorrect, lastReviewed, nextReview } }
      practice: {
        source: 'current',        // 'current' | 'upload'
        uploadedDict: null,       // dicionário carregado avulso (não sobrescreve State.dictionary)
        activeDict: null,         // ponteiro pro dicionário usado nesta sessão
        queue: [],                // lista de palavras (keys) da sessão atual, na ordem de exibição
        currentIndex: 0,
        correctCount: 0,
        wrongWords: [],           // [{ word, entry }] erradas na sessão, para o resumo
        currentWord: null,
        lastCheckCorrect: null,   // resultado do match automático da tentativa atual
      },
      // ── Novo: Configuração visual personalizada ──
      visualConfig: {
        word: {
          color: '#c2410c',
          thickness: '2px',
          opacity: 1,
          style: 'dashed', // dashed | solid | dotted
          offset: '1px'
        },
        suffixState: {
          color: '#16a34a',
          thickness: '1.5px',
          opacity: 0.75,
          style: 'dashed',
          offset: '1px',
          useWordOffset: true
        },
        suffixDerivative: {
          color: '#2563eb',
          thickness: '1.5px',
          opacity: 0.75,
          style: 'dashed',
          offset: '1px',
          useWordOffset: true
        },
        suffix: {
          visible: true
        },
        extra: {
          color: '#16a34a',
          thickness: '1.5px',
          opacity: 0.75,
          style: 'dashed'
        },
        shortcuts: {
          openSearch: 'Ctrl+K',
          openPdfSearch: 'Ctrl+F',
          toggleSidebar: 'Ctrl+Alt+D',
          toggleVisualPanel: 'Ctrl+Alt+P'
        }
      }
    };

    // ═══════════════════════════════════════════════════════════
    // DICIONÁRIO PADRÃO (seed)
    // ═══════════════════════════════════════════════════════════
    const DEFAULT_DICT = {
      "very": { "translations": ["muito", "bastante"], "examples": [] },
      "really": { "translations": ["realmente", "de fato"], "examples": [] },
      "still": { "translations": ["ainda", "mesmo assim"], "examples": [] },
      "again": { "translations": ["novamente", "de novo"], "examples": [] },
      "always": { "translations": ["sempre"], "examples": [] },
      "never": { "translations": ["nunca"], "examples": [] },
      "sometimes": { "translations": ["às vezes"], "examples": [] },
      "usually": { "translations": ["geralmente"], "examples": [] },

      "because": { "translations": ["porque", "pois"], "examples": [] },
      "why": { "translations": ["por que"], "examples": [] },
      "yes": { "translations": ["sim"], "examples": [] },
      "nope": { "translations": ["não", "não mesmo"], "examples": [] },
      "okay": { "translations": ["ok", "tudo bem"], "examples": [] },

      "want": { "translations": ["querer"], "examples": [] },
      "need": { "translations": ["precisar", "necessitar"], "examples": [] },
      "try": { "translations": ["tentar"], "examples": [] },
      "leave": { "translations": ["deixar", "sair"], "examples": [] },
      "feel": { "translations": ["sentir"], "examples": [] },

      "life": { "translations": ["vida"], "examples": [] },
      "day": { "translations": ["dia"], "examples": [] },
      "night": { "translations": ["noite"], "examples": [] },
      "year": { "translations": ["ano"], "examples": [] },
      "week": { "translations": ["semana"], "examples": [] },

      "home": { "translations": ["casa", "lar"], "examples": [] },
      "place": { "translations": ["lugar", "local"], "examples": [] },
      "area": { "translations": ["área", "região"], "examples": [] },

      "man": { "translations": ["homem"], "examples": [] },
      "woman": { "translations": ["mulher"], "examples": [] },
      "child": { "translations": ["criança"], "examples": [] },
      "": { "translations": ["família"], "examples": [] },
      "friend": { "translations": ["amigo", "amiga"], "examples": [] },

      "good": { "translations": ["bom", "boa"], "examples": [] },
      "bad": { "translations": ["ruim", "mau"], "examples": [] },
      "best": { "translations": ["melhor"], "examples": [] },
      "worst": { "translations": ["pior"], "examples": [] },

      "big": { "translations": ["grande"], "examples": [] },
      "long": { "translations": ["longo"], "examples": [] },
      "short": { "translations": ["curto", "baixo"], "examples": [] },

      "start": { "translations": ["começar", "iniciar"], "examples": [] },
      "end": { "translations": ["fim", "terminar"], "examples": [] },
      "begin": { "translations": ["começar", "iniciar"], "examples": [] },

      "open": { "translations": ["abrir", "aberto"], "examples": [] },
      "close": { "translations": ["fechar", "perto"], "examples": [] },

      "read": { "translations": ["ler"], "examples": [] },
      "write": { "translations": ["escrever"], "examples": [] },
      "speak": { "translations": ["falar"], "examples": [] },
      "listen": { "translations": ["ouvir", "escutar"], "examples": [] },

      "buy": { "translations": ["comprar"], "examples": [] },
      "sell": { "translations": ["vender"], "examples": [] },
      "pay": { "translations": ["pagar"], "examples": [] },

      "food": { "translations": ["comida"], "examples": [] },
      "water": { "translations": ["água"], "examples": [] },
      "money": { "translations": ["dinheiro"], "examples": [] },

      "car": { "translations": ["carro"], "examples": [] },
      "house": { "translations": ["casa"], "examples": [] },
      "room": { "translations": ["quarto", "sala"], "examples": [] },

      "city": { "translations": ["cidade"], "examples": [] },
      "country": { "translations": ["país"], "examples": [] },

      "job": { "translations": ["trabalho", "emprego"], "examples": [] },
      "business": { "translations": ["negócio", "empresa"], "examples": [] },

      "question": { "translations": ["pergunta", "questão"], "examples": [] },
      "answer": { "translations": ["resposta"], "examples": [] },

      "idea": { "translations": ["ideia"], "examples": [] },
      "plan": { "translations": ["plano"], "examples": [] },
      "goal": { "translations": ["objetivo", "meta"], "examples": [] },

      "reason": { "translations": ["razão", "motivo"], "examples": [] },
      "result": { "translations": ["resultado"], "examples": [] },

      "change": { "translations": ["mudar", "mudança"], "examples": [] },
      "create": { "translations": ["criar"], "examples": [] },
      "build": { "translations": ["construir"], "examples": [] },

      "help": { "translations": ["ajudar", "ajuda"], "examples": [] },
      "support": { "translations": ["suporte", "apoiar"], "examples": [] },

      "important": { "translations": ["importante"], "examples": [] },
      "necessary": { "translations": ["necessário"], "examples": [] },
      "possible": { "translations": ["possível"], "examples": [] },

      "easy": { "translations": ["fácil"], "examples": [] },
      "hard": { "translations": ["difícil", "duro"], "examples": [] },

      "right": { "translations": ["certo", "direita"], "examples": [] },
      "left": { "translations": ["esquerda"], "examples": [] },

      "next": { "translations": ["próximo"], "examples": [] },
      "last": { "translations": ["último"], "examples": [] },

      "early": { "translations": ["cedo"], "examples": [] },
      "late": { "translations": ["tarde", "atrasado"], "examples": [] },
      "the": { "translations": ["o", "a", "os", "as"], "examples": [] },
      "of": { "translations": ["de", "do", "da"], "examples": [] },
      "and": { "translations": ["e"], "examples": [] },
      "in": { "translations": ["em", "no", "na"], "examples": [] },
      "to": { "translations": ["para", "a"], "examples": [] },
      "is": { "translations": ["é", "está"], "examples": [] },
      "are": { "translations": ["são", "estão"], "examples": [] },
      "was": { "translations": ["foi", "era", "estava"], "examples": [] },
      "has": { "translations": ["tem", "possui"], "examples": [] },
      "have": { "translations": ["ter", "possuir"], "examples": [] },
      "with": { "translations": ["com"], "examples": [] },
      "this": { "translations": ["este", "esta", "isso"], "examples": [] },
      "that": { "translations": ["que", "esse", "aquele"], "examples": [] },
      "from": { "translations": ["de", "do", "da", "desde"], "examples": [] },
      "by": { "translations": ["por", "pelo", "pela"], "examples": [] },
      "as": { "translations": ["como", "enquanto", "pois"], "examples": [] },
      "on": { "translations": ["em", "sobre", "no", "na"], "examples": [] },
      "at": { "translations": ["em", "no", "na", "às"], "examples": [] },
      "it": { "translations": ["ele", "ela", "isso", "o"], "examples": [] },
      "an": { "translations": ["um", "uma"], "examples": [] },
      "not": { "translations": ["não"], "examples": [] },
      "be": { "translations": ["ser", "estar"], "examples": [] },
      "which": { "translations": ["que", "qual", "o qual"], "examples": [] },
      "but": { "translations": ["mas", "porém"], "examples": [] },
      "or": { "translations": ["ou"], "examples": [] },
      "for": { "translations": ["para", "por"], "examples": [] },
      "can": { "translations": ["pode", "consegue", "poder"], "examples": [] },
      "will": { "translations": ["irá", "vai", "futuro"], "examples": [] },
      "would": { "translations": ["iria", "gostaria"], "examples": [] },
      "about": { "translations": ["sobre", "acerca de", "aproximadamente"], "examples": [{ "original": "Tell me about it", "translated": "Conte-me sobre isso" }] },
      "between": { "translations": ["entre"], "examples": [] },
      "through": { "translations": ["através de", "por meio de"], "examples": [] },
      "when": { "translations": ["quando"], "examples": [] },
      "where": { "translations": ["onde", "aonde"], "examples": [] },
      "how": { "translations": ["como", "quão"], "examples": [] },
      "what": { "translations": ["o que", "qual"], "examples": [] },
      "also": { "translations": ["também", "além disso"], "examples": [] },
      "than": { "translations": ["do que", "que"], "examples": [] },
      "more": { "translations": ["mais"], "examples": [] },
      "other": { "translations": ["outro", "outra"], "examples": [] },
      "into": { "translations": ["em", "dentro de", "para dentro"], "examples": [] },
      "only": { "translations": ["apenas", "somente", "só"], "examples": [] },
      "after": { "translations": ["após", "depois de"], "examples": [] },
      "before": { "translations": ["antes de", "antes"], "examples": [] },
      "such": { "translations": ["tal", "tais", "como"], "examples": [] },
      "even": { "translations": ["até mesmo", "mesmo", "ainda"], "examples": [] },
      "most": { "translations": ["mais", "maioria", "a maioria"], "examples": [] },
      "may": { "translations": ["pode", "talvez", "maio"], "examples": [] },
      "their": { "translations": ["seu", "sua", "deles", "delas"], "examples": [] },
      "they": { "translations": ["eles", "elas"], "examples": [] },
      "however": { "translations": ["no entanto", "porém", "todavia"], "examples": [] },
      "therefore": { "translations": ["portanto", "logo", "assim"], "examples": [] },
      "although": { "translations": ["embora", "apesar de", "ainda que"], "examples": [] },
      "since": { "translations": ["desde", "visto que", "já que"], "examples": [] },
      "both": { "translations": ["ambos", "ambas", "os dois"], "examples": [] },
      "each": { "translations": ["cada", "cada um"], "examples": [] },
      "first": { "translations": ["primeiro", "primeiramente"], "examples": [] },
      "time": { "translations": ["tempo", "vez", "hora"], "examples": [{ "original": "Time flies", "translated": "O tempo voa" }] },
      "work": { "translations": ["trabalho", "obra", "funcionar"], "examples": [{ "original": "I need to work harder", "translated": "Preciso trabalhar mais" }] },
      "people": { "translations": ["pessoas", "povo", "gente"], "examples": [] },
      "world": { "translations": ["mundo"], "examples": [{ "original": "The world is changing", "translated": "O mundo está mudando" }] },
      "new": { "translations": ["novo", "nova", "recente"], "examples": [] },
      "important": { "translations": ["importante", "relevante"], "examples": [] },
      "different": { "translations": ["diferente", "distinto"], "examples": [] },
      "used": { "translations": ["usado", "utilizado", "costumava"], "examples": [] },
      "system": { "translations": ["sistema"], "examples": [] },
      "data": { "translations": ["dados", "informações"], "examples": [] },
      "research": { "translations": ["pesquisa", "investigação"], "examples": [] },
      "model": { "translations": ["modelo"], "examples": [] },
      "language": { "translations": ["linguagem", "idioma", "língua"], "examples": [] },
      "training": { "translations": ["treinamento", "treino"], "examples": [] },
      "learning": { "translations": ["aprendizado", "aprendizagem"], "examples": [] },
      "based": { "translations": ["baseado", "fundamentado"], "examples": [] },
      "using": { "translations": ["usando", "utilizando", "através de"], "examples": [] },
      "results": { "translations": ["resultados"], "examples": [] },
      "information": { "translations": ["informação", "informações"], "examples": [] },
      "process": { "translations": ["processo", "processar"], "examples": [] },
      "example": { "translations": ["exemplo"], "examples": [] },
      "shows": { "translations": ["mostra", "indica", "demonstra"], "examples": [] },
      "specific": { "translations": ["específico", "particular"], "examples": [] },
      "performance": { "translations": ["desempenho", "performance"], "examples": [] },
      "approach": { "translations": ["abordagem", "método", "aproximar-se"], "examples": [] },
      "while": { "translations": ["enquanto", "ao passo que"], "examples": [] },
      "provide": { "translations": ["fornecer", "prover", "oferecer"], "examples": [] },
      "number": { "translations": ["número"], "examples": [] },
      "high": { "translations": ["alto", "elevado"], "examples": [] },
      "large": { "translations": ["grande", "amplo"], "examples": [] },
      "small": { "translations": ["pequeno", "reduzido"], "examples": [] },
      "given": { "translations": ["dado", "fornecido", "considerando"], "examples": [] },
      "within": { "translations": ["dentro de", "em"], "examples": [] },
      "requires": { "translations": ["requer", "exige", "necessita"], "examples": [] },
      "without": { "translations": ["sem"], "examples": [] },
      "across": { "translations": ["ao longo de", "através de", "em"], "examples": [] },
      "often": { "translations": ["frequentemente", "muitas vezes"], "examples": [] },
      "same": { "translations": ["mesmo", "mesma", "igual"], "examples": [] },
      "those": { "translations": ["aqueles", "aquelas", "esses"], "examples": [] },
      "these": { "translations": ["estes", "estas", "esses"], "examples": [] },
      "then": { "translations": ["então", "depois", "em seguida"], "examples": [] },
      "should": { "translations": ["deveria", "deve", "precisaria"], "examples": [] },
      "over": { "translations": ["sobre", "acima de", "mais de"], "examples": [] },
      "well": { "translations": ["bem", "poço", "além disso"], "examples": [] },
      "he": { "translations": ["ele"], "examples": [] },
      "she": { "translations": ["ela"], "examples": [] },
      "we": { "translations": ["nós"], "examples": [] },
      "you": { "translations": ["você", "vocês", "tu"], "examples": [] },
      "our": { "translations": ["nosso", "nossa"], "examples": [] },
      "its": { "translations": ["seu", "sua", "dele", "dela"], "examples": [] },
      "been": { "translations": ["sido", "estado"], "examples": [] },
      "all": { "translations": ["todos", "tudo", "todo"], "examples": [] },
      "any": { "translations": ["qualquer", "algum", "nenhum"], "examples": [] },
      "there": { "translations": ["lá", "ali", "há"], "examples": [] },
      "one": { "translations": ["um", "uma", "um(a)"], "examples": [] },
      "two": { "translations": ["dois", "duas"], "examples": [] },
      "use": { "translations": ["usar", "utilizar", "uso"], "examples": [] },
      "make": { "translations": ["fazer", "criar", "tornar"], "examples": [] },
      "way": { "translations": ["modo", "forma", "caminho"], "examples": [] },
      "many": { "translations": ["muitos", "muitas", "vários"], "examples": [] },
      "very": { "translations": ["muito", "bastante"], "examples": [] },
      "need": { "translations": ["precisar", "necessitar", "necessidade"], "examples": [] },
      "possible": { "translations": ["possível"], "examples": [] },
      "could": { "translations": ["poderia", "conseguia"], "examples": [] },
      "must": { "translations": ["deve", "precisa", "tem que"], "examples": [] },
      "does": { "translations": ["faz", "realiza"], "examples": [] },
      "do": { "translations": ["fazer", "realizar"], "examples": [] },
      "did": { "translations": ["fez", "realizou"], "examples": [] },
      "some": { "translations": ["algum", "alguma", "alguns", "algumas"], "examples": [] },
      "his": { "translations": ["seu", "dele"], "examples": [] },
      "her": { "translations": ["sua", "dela", "ela (obj)"], "examples": [] },
      "him": { "translations": ["ele (obj)", "o"], "examples": [] },
      "us": { "translations": ["nós", "nos"], "examples": [] },
      "my": { "translations": ["meu", "minha"], "examples": [] },
      "your": { "translations": ["seu", "sua", "teu", "tua"], "examples": [] },
      "their": { "translations": ["seu", "sua", "deles"], "examples": [] },
      "if": { "translations": ["se", "caso"], "examples": [] },
      "up": { "translations": ["acima", "para cima", "cima"], "examples": [] },
      "down": { "translations": ["abaixo", "para baixo"], "examples": [] },
      "out": { "translations": ["fora", "para fora"], "examples": [] },
      "no": { "translations": ["não", "nenhum"], "examples": [] },
      "so": { "translations": ["então", "portanto", "assim", "tão"], "examples": [] },
      "now": { "translations": ["agora", "atualmente"], "examples": [] },
      "just": { "translations": ["apenas", "somente", "justo"], "examples": [] },
      "like": { "translations": ["como", "igual a", "gostar"], "examples": [] },
      "know": { "translations": ["saber", "conhecer"], "examples": [] },
      "think": { "translations": ["pensar", "achar", "crer"], "examples": [] },
      "said": { "translations": ["disse", "falou"], "examples": [] },
      "get": { "translations": ["obter", "pegar", "conseguir"], "examples": [] },
      "see": { "translations": ["ver", "enxergar", "entender"], "examples": [] },
      "look": { "translations": ["olhar", "parecer", "aparência"], "examples": [] },
      "come": { "translations": ["vir", "chegar"], "examples": [] },
      "go": { "translations": ["ir", "andar"], "examples": [] },
      "give": { "translations": ["dar", "oferecer"], "examples": [] },
      "take": { "translations": ["pegar", "tomar", "levar"], "examples": [] },
      "show": { "translations": ["mostrar", "exibir", "demonstrar"], "examples": [] },
      "tell": { "translations": ["contar", "dizer", "informar"], "examples": [] },
      "call": { "translations": ["chamar", "ligar", "chamada"], "examples": [] },
      "keep": { "translations": ["manter", "guardar"], "examples": [] },
      "set": { "translations": ["definir", "conjunto", "ajustar"], "examples": [] },
      "run": { "translations": ["correr", "executar", "rodar"], "examples": [] },
      "put": { "translations": ["colocar", "pôr"], "examples": [] },
      "following": { "translations": ["seguindo", "a seguir", "seguinte"], "examples": [] },
      "known": { "translations": ["conhecido", "sabido"], "examples": [] },
      "called": { "translations": ["chamado", "denominado"], "examples": [] },
      "general": { "translations": ["geral", "comum"], "examples": [] },
      "public": { "translations": ["público"], "examples": [] },
      "group": { "translations": ["grupo", "conjunto"], "examples": [] },
      "term": { "translations": ["termo", "período", "prazo"], "examples": [] },
      "problem": { "translations": ["problema", "questão"], "examples": [] },
      "value": { "translations": ["valor", "valia"], "examples": [] },
      "function": { "translations": ["função", "funcionar"], "examples": [] },
      "class": { "translations": ["classe", "aula", "turma"], "examples": [] },
      "type": { "translations": ["tipo", "categoria", "digitar"], "examples": [] },
      "level": { "translations": ["nível", "patamar"], "examples": [] },
      "point": { "translations": ["ponto", "pontuar", "indicar"], "examples": [] },
      "input": { "translations": ["entrada", "inserção", "dado de entrada"], "examples": [] },
      "output": { "translations": ["saída", "resultado", "produção"], "examples": [] },
      "network": { "translations": ["rede", "rede neural"], "examples": [] },
      "layer": { "translations": ["camada"], "examples": [] },
      "vector": { "translations": ["vetor"], "examples": [] },
      "matrix": { "translations": ["matriz"], "examples": [] },
      "feature": { "translations": ["característica", "recurso", "funcionalidade"], "examples": [] },
      "error": { "translations": ["erro", "falha"], "examples": [] },
      "loss": { "translations": ["perda", "prejuízo", "função de perda"], "examples": [] },
      "gradient": { "translations": ["gradiente"], "examples": [] },
      "weight": { "translations": ["peso", "ponderação"], "examples": [] },
      "parameter": { "translations": ["parâmetro"], "examples": [] },
      "distribution": { "translations": ["distribuição"], "examples": [] },
      "probability": { "translations": ["probabilidade"], "examples": [] },
      "sample": { "translations": ["amostra", "exemplo", "amostrar"], "examples": [] },
      "method": { "translations": ["método", "técnica"], "examples": [] },
      "algorithm": { "translations": ["algoritmo"], "examples": [] },
      "task": { "translations": ["tarefa", "missão"], "examples": [] },
      "dataset": { "translations": ["conjunto de dados", "base de dados"], "examples": [] },
      "test": { "translations": ["teste", "testar", "examinar"], "examples": [] },
      "evaluation": { "translations": ["avaliação", "análise"], "examples": [] },
      "accuracy": { "translations": ["precisão", "exatidão", "acurácia"], "examples": [] },
      "baseline": { "translations": ["linha de base", "referência"], "examples": [] },
      "benchmark": { "translations": ["benchmark", "referência de desempenho"], "examples": [] },
      "state": { "translations": ["estado", "condição", "afirmar"], "examples": [] },
      "attention": { "translations": ["atenção", "mecanismo de atenção"], "examples": [] },
      "context": { "translations": ["contexto"], "examples": [] },
      "token": { "translations": ["token", "símbolo"], "examples": [] },
      "text": { "translations": ["texto"], "examples": [] },
      "sentence": { "translations": ["sentença", "frase", "oração"], "examples": [] },
      "word": { "translations": ["palavra"], "examples": [] },
      "generate": { "translations": ["gerar", "produzir"], "examples": [] },
      "image": { "translations": ["imagem"], "examples": [] },
      "architecture": { "translations": ["arquitetura"], "examples": [] },
      "transformer": { "translations": ["transformador", "transformer"], "examples": [] },
      "fine-tuning": { "translations": ["ajuste fino", "fine-tuning"], "examples": [] },
      "pre-training": { "translations": ["pré-treino", "pre-training"], "examples": [] },
      "representation": { "translations": ["representação"], "examples": [] },
      "embedding": { "translations": ["incorporação", "embedding", "vetor de representação"], "examples": [] },
      "classification": { "translations": ["classificação"], "examples": [] },
      "score": { "translations": ["pontuação", "nota", "escore"], "examples": [] },
      "improvement": { "translations": ["melhoria", "aprimoramento"], "examples": [] },
      "significant": { "translations": ["significativo", "expressivo", "relevante"], "examples": [] },
      "compare": { "translations": ["comparar"], "examples": [] },
      "achieve": { "translations": ["alcançar", "atingir", "conseguir"], "examples": [] },
      "propose": { "translations": ["propor", "sugerir"], "examples": [] },
      "demonstrate": { "translations": ["demonstrar", "mostrar"], "examples": [] },
      "apply": { "translations": ["aplicar", "usar"], "examples": [] },
      "represent": { "translations": ["representar"], "examples": [] },
      "reduce": { "translations": ["reduzir", "diminuir"], "examples": [] },
      "increase": { "translations": ["aumentar", "incrementar"], "examples": [] },
      "improve": { "translations": ["melhorar", "aprimorar"], "examples": [] },
      "enable": { "translations": ["habilitar", "permitir", "possibilitar"], "examples": [] },
      "train": { "translations": ["treinar", "trein"], "examples": [] },
      "predict": { "translations": ["prever", "predizer", "predizer"], "examples": [] },
      "understand": { "translations": ["entender", "compreender"], "examples": [] },
      "introduce": { "translations": ["introduzir", "apresentar"], "examples": [] },
      "present": { "translations": ["presente", "apresentar", "atual"], "examples": [] },
      "develop": { "translations": ["desenvolver", "criar"], "examples": [] },
      "note": { "translations": ["nota", "observar", "anotar"], "examples": [] },
      "section": { "translations": ["seção", "parte", "trecho"], "examples": [] },
      "figure": { "translations": ["figura", "imagem", "número"], "examples": [] },
      "table": { "translations": ["tabela", "mesa"], "examples": [] },
      "equation": { "translations": ["equação"], "examples": [] },
      "code": { "translations": ["código", "programar"], "examples": [] },
      "implementation": { "translations": ["implementação", "realização"], "examples": [] },
      "complexity": { "translations": ["complexidade"], "examples": [] },
      "efficient": { "translations": ["eficiente"], "examples": [] },
      "effective": { "translations": ["eficaz", "efetivo"], "examples": [] },
      "robust": { "translations": ["robusto", "resiliente"], "examples": [] },
      "novel": { "translations": ["novo", "inovador", "romance (livro)"], "examples": [] },
      "previous": { "translations": ["anterior", "precedente", "prévio"], "examples": [] },
      "existing": { "translations": ["existente", "atual"], "examples": [] },
      "recent": { "translations": ["recente", "recentemente"], "examples": [] },
      "future": { "translations": ["futuro"], "examples": [] },
      "paper": { "translations": ["artigo", "papel", "trabalho"], "examples": [] },
      "article": { "translations": ["artigo"], "examples": [] },
      "study": { "translations": ["estudo", "estudar"], "examples": [] },
      "analysis": { "translations": ["análise"], "examples": [] },
      "experiment": { "translations": ["experimento", "experimentar"], "examples": [] },
      "conclusion": { "translations": ["conclusão"], "examples": [] },
      "introduction": { "translations": ["introdução"], "examples": [] },
      "abstract": { "translations": ["resumo", "abstrato", "abstrair"], "examples": [] },
      "summary": { "translations": ["resumo", "sumário"], "examples": [] },
      "related": { "translations": ["relacionado", "relevante"], "examples": [] },
      "similar": { "translations": ["similar", "semelhante", "parecido"], "examples": [] },
      "compared": { "translations": ["comparado", "em relação a"], "examples": [] },
    };